config/routes.rb
Bookshop::Application.routes.draw do

  resources :sessions

  resources :users

  resources :user_types

  get :login , to: "sessions#new"    , as: :login
  
  get :logout, to: "sessions#destroy", as: :logout
  
  get :signup, to: "users#new"       , as: :signup
  
  get :about  , to: "pages#about"     , as: :about
  get :legal  , to: "pages#legal"     , as: :legal
  get :contact, to: "pages#contact"   , as: :contact
  get :privacy, to: "pages#privacy"   , as: :privacy
  
  match 'pages/:id' => 'pages#show'

  root :to => 'pages#home'
end

app/models/user.rb
require 'permissions'

class User < ActiveRecord::Base
  has_secure_password

  belongs_to :user_type
  attr_accessible :email, :password, :password_confirmation, :role

  validates_uniqueness_of :email

  def role
    p = read_attribute(:role)
    Permissions.new(p)
  end

  def role=(role)
    p = Permissions.new(role)
    write_attribute(:role, p.to_i)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session and session[:user_id]
    rescue ActiveRecord::RecordNotFound
    end
    @current_user
  end

  def is_admin
    current_user.role.is_administrator? if current_user
  end

  def is_admin_or_user
    session[:user_id] == params[:user_id] if (session[:user_id] && params[:user_id]) || current_user.role.is_administrator? if current_user
  end

helper_method :current_user, :is_admin, :is_admin_or_user

  def require_login
    unless current_user
      flash.now.alert = "Action requires you are logged in"
      redirect_to login_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :require_login
    
  rescue_from ActionView::MissingTemplate, :with => :invalid_page
  
  def show
    render params[:id]
  end

  def invalid_page
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Welcome!"
    else
      flash.now.alert = "Email or password is invalid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil if session[:user_id]
    redirect_to root_url, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]
  before_filter :is_admin_or_user, only: [:show, :edit, :update]
  before_filter :is_admin, only: [:index, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title The Mighty Pie Shop
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #container
      #header
        %h2 Welcome to The Mighty Pie Shop.
        %h3 Making awesome pies - since RSN.
        .navlinks
          - if current_user
            Signed in as #{current_user.email}
            = link_to "Edit profile", edit_user_path(current_user)
            = link_to "Logout", logout_path
          -else
            = link_to "Sign Up", signup_path
            or
            = link_to "Log In", login_path
      #sidebar
        = render_cell :sidebar, :show, user: current_user
      #content
        - flash.each do |name,msg|
          = content_tag :div, msg, id: "flash_#{name}"
        = yield
      #footer
        #footerbar
          %ul.footlinks
            %li= link_to :About, about_path
            %li= link_to :Legal, legal_path
            %li= link_to :Contact, contact_path
            %li= link_to :Privacy, privacy_path

app/views/pages/about.html.haml
%h2 About Us

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in justo massa, eget vulputate quam. Etiam pulvinar risus sit amet ipsum rhoncus id euismod nulla convallis. Nullam pharetra luctus neque, vitae pulvinar sem fringilla a. Donec turpis lacus, adipiscing a facilisis ac, viverra nec urna. Pellentesque elementum porta nunc, in aliquet lorem congue et. Mauris pretium posuere felis, feugiat dictum justo euismod eget. Sed in elit nec erat consequat imperdiet. Nulla vestibulum magna in orci euismod sit amet faucibus diam semper. In vitae mattis dui.

%p Suspendisse nec urna elit. Nam in dui velit. Mauris eget pharetra orci. Donec magna neque, suscipit vitae pulvinar ultricies, accumsan sit amet felis. Sed rhoncus posuere sapien in tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin porta volutpat ornare. Suspendisse potenti. Nam id mi vitae libero pulvinar iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sollicitudin, sapien non tempus fermentum, est erat ullamcorper tellus, a tempor nulla arcu tincidunt orci. Mauris velit mauris, lobortis eget accumsan a, ornare vel orci. Donec quis mauris tortor, in tempus nisl.

%p Praesent eget tortor non ligula tincidunt semper commodo sit amet risus. Ut velit orci, laoreet sit amet dapibus a, mollis sit amet justo. Suspendisse mollis lacinia convallis. Curabitur lobortis elit nibh, quis sollicitudin augue. Proin dictum, nisi vel pulvinar consectetur, sem nisi rhoncus elit, id faucibus dolor ligula in ipsum. Vivamus a ante et tellus lacinia lobortis. Integer a sapien elit.

app/views/pages/contact.html.haml
%h2 How to Contact Us

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in justo massa, eget vulputate quam. Etiam pulvinar risus sit amet ipsum rhoncus id euismod nulla convallis. Nullam pharetra luctus neque, vitae pulvinar sem fringilla a. Donec turpis lacus, adipiscing a facilisis ac, viverra nec urna. Pellentesque elementum porta nunc, in aliquet lorem congue et. Mauris pretium posuere felis, feugiat dictum justo euismod eget. Sed in elit nec erat consequat imperdiet. Nulla vestibulum magna in orci euismod sit amet faucibus diam semper. In vitae mattis dui.

%p Suspendisse nec urna elit. Nam in dui velit. Mauris eget pharetra orci. Donec magna neque, suscipit vitae pulvinar ultricies, accumsan sit amet felis. Sed rhoncus posuere sapien in tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin porta volutpat ornare. Suspendisse potenti. Nam id mi vitae libero pulvinar iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sollicitudin, sapien non tempus fermentum, est erat ullamcorper tellus, a tempor nulla arcu tincidunt orci. Mauris velit mauris, lobortis eget accumsan a, ornare vel orci. Donec quis mauris tortor, in tempus nisl.

%p Praesent eget tortor non ligula tincidunt semper commodo sit amet risus. Ut velit orci, laoreet sit amet dapibus a, mollis sit amet justo. Suspendisse mollis lacinia convallis. Curabitur lobortis elit nibh, quis sollicitudin augue. Proin dictum, nisi vel pulvinar consectetur, sem nisi rhoncus elit, id faucibus dolor ligula in ipsum. Vivamus a ante et tellus lacinia lobortis. Integer a sapien elit.

app/views/pages/home.html.haml
%h2 El Problem

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in justo massa, eget vulputate quam. Etiam pulvinar risus sit amet ipsum rhoncus id euismod nulla convallis. Nullam pharetra luctus neque, vitae pulvinar sem fringilla a. Donec turpis lacus, adipiscing a facilisis ac, viverra nec urna. Pellentesque elementum porta nunc, in aliquet lorem congue et. Mauris pretium posuere felis, feugiat dictum justo euismod eget. Sed in elit nec erat consequat imperdiet. Nulla vestibulum magna in orci euismod sit amet faucibus diam semper. In vitae mattis dui.

%p Suspendisse nec urna elit. Nam in dui velit. Mauris eget pharetra orci. Donec magna neque, suscipit vitae pulvinar ultricies, accumsan sit amet felis. Sed rhoncus posuere sapien in tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin porta volutpat ornare. Suspendisse potenti. Nam id mi vitae libero pulvinar iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sollicitudin, sapien non tempus fermentum, est erat ullamcorper tellus, a tempor nulla arcu tincidunt orci. Mauris velit mauris, lobortis eget accumsan a, ornare vel orci. Donec quis mauris tortor, in tempus nisl.

%p Praesent eget tortor non ligula tincidunt semper commodo sit amet risus. Ut velit orci, laoreet sit amet dapibus a, mollis sit amet justo. Suspendisse mollis lacinia convallis. Curabitur lobortis elit nibh, quis sollicitudin augue. Proin dictum, nisi vel pulvinar consectetur, sem nisi rhoncus elit, id faucibus dolor ligula in ipsum. Vivamus a ante et tellus lacinia lobortis. Integer a sapien elit.

app/views/pages/legal.html.haml
%h2 Legal Stuff

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in justo massa, eget vulputate quam. Etiam pulvinar risus sit amet ipsum rhoncus id euismod nulla convallis. Nullam pharetra luctus neque, vitae pulvinar sem fringilla a. Donec turpis lacus, adipiscing a facilisis ac, viverra nec urna. Pellentesque elementum porta nunc, in aliquet lorem congue et. Mauris pretium posuere felis, feugiat dictum justo euismod eget. Sed in elit nec erat consequat imperdiet. Nulla vestibulum magna in orci euismod sit amet faucibus diam semper. In vitae mattis dui.

%p Suspendisse nec urna elit. Nam in dui velit. Mauris eget pharetra orci. Donec magna neque, suscipit vitae pulvinar ultricies, accumsan sit amet felis. Sed rhoncus posuere sapien in tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin porta volutpat ornare. Suspendisse potenti. Nam id mi vitae libero pulvinar iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sollicitudin, sapien non tempus fermentum, est erat ullamcorper tellus, a tempor nulla arcu tincidunt orci. Mauris velit mauris, lobortis eget accumsan a, ornare vel orci. Donec quis mauris tortor, in tempus nisl.

%p Praesent eget tortor non ligula tincidunt semper commodo sit amet risus. Ut velit orci, laoreet sit amet dapibus a, mollis sit amet justo. Suspendisse mollis lacinia convallis. Curabitur lobortis elit nibh, quis sollicitudin augue. Proin dictum, nisi vel pulvinar consectetur, sem nisi rhoncus elit, id faucibus dolor ligula in ipsum. Vivamus a ante et tellus lacinia lobortis. Integer a sapien elit.

app/views/pages/privacy.html.haml
%h2 How Your Privacy is Important to Us

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in justo massa, eget vulputate quam. Etiam pulvinar risus sit amet ipsum rhoncus id euismod nulla convallis. Nullam pharetra luctus neque, vitae pulvinar sem fringilla a. Donec turpis lacus, adipiscing a facilisis ac, viverra nec urna. Pellentesque elementum porta nunc, in aliquet lorem congue et. Mauris pretium posuere felis, feugiat dictum justo euismod eget. Sed in elit nec erat consequat imperdiet. Nulla vestibulum magna in orci euismod sit amet faucibus diam semper. In vitae mattis dui.

%p Suspendisse nec urna elit. Nam in dui velit. Mauris eget pharetra orci. Donec magna neque, suscipit vitae pulvinar ultricies, accumsan sit amet felis. Sed rhoncus posuere sapien in tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin porta volutpat ornare. Suspendisse potenti. Nam id mi vitae libero pulvinar iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sollicitudin, sapien non tempus fermentum, est erat ullamcorper tellus, a tempor nulla arcu tincidunt orci. Mauris velit mauris, lobortis eget accumsan a, ornare vel orci. Donec quis mauris tortor, in tempus nisl.

%p Praesent eget tortor non ligula tincidunt semper commodo sit amet risus. Ut velit orci, laoreet sit amet dapibus a, mollis sit amet justo. Suspendisse mollis lacinia convallis. Curabitur lobortis elit nibh, quis sollicitudin augue. Proin dictum, nisi vel pulvinar consectetur, sem nisi rhoncus elit, id faucibus dolor ligula in ipsum. Vivamus a ante et tellus lacinia lobortis. Integer a sapien elit.

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label "Confirmation"
    = f.password_field :password_confirmation
  .field
    = f.fields_for :user do |builder|
      = builder.label "Role"
      = f.select 'role', Permissions::ROLEMAP
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th User Type
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.user_type.typename if user.user_type
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User Sign up
 
= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%h2 User Listing
%p
  %b Email:
  = @user.email
%p
  %b User Type:
  = @user.user_type.typename if @user.user_type

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path